# Generated by Django 3.2.15 on 2022-09-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_video_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='elapsed_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Elapsed time for video quality conversion', null=True, verbose_name='Elapsed Time'),
        ),
    ]
